name: base_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get_storage: ^2.0.3
  dio: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.0
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  get_cli: ^1.6.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

get_cli: 
  separator: .

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

